version: '3.8'

services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./website:/app
      - /app/node_modules

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - db
      - redis

  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - JUPYTER_TOKEN=sector-h

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=sectorh
      - POSTGRES_PASSWORD=sectorh
      - POSTGRES_DB=sectorh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
